language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y groff; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build-osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./build-linux-64.sh; fi
