sudo: required
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y groff
script:
  - mkdir build
  - cd build
  - cmake .. && make VERBOSE=1 && make check
