version: 1.0.{build}
build_script:
- ps: >-
    $env:Path += ";C:\cygwin64\bin"

    mkdir cmakebuild

    cd cmakebuild

    cmake ..

    msbuild PACKAGE.vcxproj /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: cmakebuild\*.zip