platform:
- x86
- x64

version: 1.0.{build}
install:
- ps: Invoke-WebRequest 'https://github.com/embree/embree/releases/download/v2.10.0/embree-2.10.0.x64.windows.zip' -OutFile 'embree64.zip'
- ps: 7z x embree64.zip -oc:\
- ps: Invoke-WebRequest 'https://github.com/embree/embree/releases/download/v2.10.0/embree-2.10.0.win32.windows.zip' -OutFile 'embree.zip'
- ps: 7z x embree.zip -oc:\
build_script:
- ps: >-
    $env:Path += ";C:\cygwin64\bin"

    mkdir cmakebuild

    cd cmakebuild

    If ($env:Platform -Match "x64") {
      cmake .. -T v140_xp -Dembree_DIR="c:/embree-2.10.0.x64.windows/lib/cmake/embree-2.10.0" -DCMAKE_GENERATOR_PLATFORM=x64
    } Else {
      cmake .. -T v140_xp -Dembree_DIR="c:/embree-2.10.0.win32.windows/lib/cmake/embree-2.10.0"
    }

    msbuild PACKAGE.vcxproj /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: cmakebuild\*.zip